import type { MonetaryValueDto } from "./MonetaryValueDto";

export interface ProjectDtos {
  Items: ProjectDto[] | null;
}

export interface ProjectDto {
  Id: string;
  Number: string | null;
  Name: string | null;
  ExternalId: string | null;
  Status: string | null;
  WorkflowStepName: string | null;
  WorkflowStepIndex: number | null;
  // CreatedBy: UserIdentifierModel | null;
  // CreatedOn: string;
  // ModifiedBy: UserIdentifierModel | null;
  // ModifiedOn: string | null;
  // Customer: OfficeIdentifierModel | null;
  // Address: AddressModel | null;
  // BidPercentageMargin: number | null;
  // PlannedPercentageMargin: number | null;
  // ActualPercentageMargin: number | null;
  // Opportunity: ProjectConvertedFromOpportunityModel | null;
  // OriginalPreTaxDraftingRevenue: MonetaryValueDto | null;
  // OriginalPreTaxFabricationRevenue: MonetaryValueDto | null;
  // OriginalPreTaxProductRevenue: MonetaryValueDto | null;
  // OriginalDraftingSalesTax: MonetaryValueDto | null;
  // OriginalFabricationSalesTax: MonetaryValueDto | null;
  // OriginalProductSalesTax: MonetaryValueDto | null;
  // OriginalDraftingSalesTaxPercentage: number | null;
  // OriginalFabricationSalesTaxPercentage: number | null;
  // OriginalProductSalesTaxPercentage: number | null;
  // OriginalTotalDraftingAmount: MonetaryValueDto | null;
  // OriginalTotalFabricationAmount: MonetaryValueDto | null;
  // OriginalTotalProductAmount: MonetaryValueDto | null;
  // OriginalPreTaxInstallRevenue: MonetaryValueDto | null;
  // OriginalInstallSalesTax: MonetaryValueDto | null;
  // OriginalInstallSalesTaxPercentage: number | null;
  // OriginalTotalInstallAmount: MonetaryValueDto | null;
  // OriginalPreTaxTotalRevenue: MonetaryValueDto | null;
  // OriginalTotalSalesTax: MonetaryValueDto | null;
  // OriginalTotalSalesTaxPercentage: number | null;
  // OriginalTotalContract: MonetaryValueDto | null;
  // PreTaxProductRevenue: MonetaryValueDto | null;
  // ProductSalesTax: MonetaryValueDto | null;
  // ProductSalesTaxPercentage: number | null;
  // TotalProductAmount: MonetaryValueDto | null;
  // PreTaxInstallRevenue: MonetaryValueDto | null;
  // InstallSalesTax: MonetaryValueDto | null;
  // InstallSalesTaxPercentage: number | null;
  // TotalInstallAmount: MonetaryValueDto | null;
  // PreTaxTotalRevenue: MonetaryValueDto | null;
  // TotalSalesTax: MonetaryValueDto | null;
  // TotalSalesTaxPercentage: number | null;
  // TotalContract: MonetaryValueDto | null;
  // EstimatedBudgetGroupsTotalCost: MonetaryValueDto | null;
  // PendingBudgetGroupsTotalCost: MonetaryValueDto | null;
  // PlannedBudgetGroupsTotalCost: MonetaryValueDto | null;
  // ActualBudgetGroupsTotalCost: MonetaryValueDto | null;
  // EstimatedLaborItemsTotalCost: MonetaryValueDto | null;
  // PendingLaborItemsTotalCost: MonetaryValueDto | null;
  PlannedLaborItemsTotalCost: MonetaryValueDto | null;
  // ActualLaborItemsTotalCost: MonetaryValueDto | null;
  // EstimatedLaborItemsTotalHours: string | null;
  // PendingLaborItemsTotalHours: string | null;
  // PlannedLaborItemsTotalHours: string | null;
  // ActualLaborItemsTotalHours: string | null;
  // EstimatedGrandTotalCost: MonetaryValueDto | null;
  // PendingGrandTotalCost: MonetaryValueDto | null;
  // PlannedGrandTotalCost: MonetaryValueDto | null;
  // ActualGrandTotalCost: MonetaryValueDto | null;
  // Estimators: UserIdentifierModel[] | null;
  // SalesPersons: UserIdentifierModel[] | null;
  // Coordinators: UserIdentifierModel[] | null;
  // Engineers: UserIdentifierModel[] | null;
  // CustomFields: ApiCustomField[] | null;
  // Installers: UserIdentifierModel[] | null;
  // MasterNote: string | null;
  // EstimatedDraftingUseTax: MonetaryValueDto | null;
  // EstimatedFabricationUseTax: MonetaryValueDto | null;
  // EstimatedInstallUseTax: MonetaryValueDto | null;
  // EstimatedTotalUseTax: MonetaryValueDto | null;
  // NextMilestone: string | null;
  // WorkflowStepIndex: number | null;
  // WorkflowStepName: string | null;
  // CloseDate: string | null;
}
